spring:
  application: 
    name: gestorclientes
  datasource:
    url: jdbc:postgresql://localhost:5432/gestorclientesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update